# Site settings
title: River Network Engine Documentation
description: > # this means to ignore newlines until "baseurl:"
  Some site description will go here
url: http://riverscapes.northarrowresearch.com/
baseurl: ""
theme: nardocs-jekyll-theme

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"


exclude:
  - LICENSE
  - README.md
  - .vendor
  - .bundle
  - Gemfile
  - Gemfile.lock
  - _config.yml